# permissions for end users to edit dnsrecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsrecord-editor-role
rules:
- apiGroups:
  - dns.k8s.marcocameriero.net
  resources:
  - dnsrecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.k8s.marcocameriero.net
  resources:
  - dnsrecords/status
  verbs:
  - get
