
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dns.k8s.marcocameriero.net
  resources:
  - dnsproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.k8s.marcocameriero.net
  resources:
  - dnsrecords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.k8s.marcocameriero.net
  resources:
  - dnsrecords/status
  verbs:
  - get
  - patch
  - update
