
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: dns-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.k8s.marcocameriero.net
  resources:
  - dnsproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.k8s.marcocameriero.net
  resources:
  - dnsproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dns.k8s.marcocameriero.net
  resources:
  - dnsrecords
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.k8s.marcocameriero.net
  resources:
  - dnsrecords/status
  verbs:
  - get
  - patch
  - update
