apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: dns-operator
  name: dns-operator

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-operator
  namespace: dns-operator
  labels:
    control-plane: dns-operator
spec:
  selector:
    matchLabels:
      control-plane: dns-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: dns-operator
    spec:
      serviceAccountName: dns-operator
      containers:
      - image: dns-operator:latest
        name: dns-operator
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
